
import 'package:flutter/material.dart';
import 'package:myapp/models/income.dart';
import 'package:myapp/services/firestore_service.dart';

class AddIncome extends StatefulWidget {
  final String userId;
  final DateTime? selectedDate;

  const AddIncome({super.key, required this.userId, this.selectedDate});

  @override
  State<AddIncome> createState() => _AddIncomeState();
}

class _AddIncomeState extends State<AddIncome> {
  final _formKey = GlobalKey<FormState>();
  double amount = 0;
  String source = '';

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(20.0),
      child: Form(
        key: _formKey,
        child: Column(
          children: <Widget>[
            const Text(
              'Add a new source of income',
              style: TextStyle(fontSize: 18.0, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 20.0),
            TextFormField(
              validator: (val) => val!.isEmpty ? 'Enter a source' : null,
              onChanged: (val) => setState(() => source = val),
              decoration: const InputDecoration(hintText: 'Source'),
            ),
            const SizedBox(height: 20.0),
            TextFormField(
              validator: (val) => val!.isEmpty ? 'Enter an amount' : null,
              onChanged: (val) => setState(() => amount = double.parse(val)),
              decoration: const InputDecoration(hintText: 'Amount'),
              keyboardType: TextInputType.number,
            ),
            const SizedBox(height: 20.0),
            ElevatedButton(
              child: const Text('Add Income'),
              onPressed: () async {
                if (_formKey.currentState!.validate()) {
                  await FirestoreService().addIncome(
                    Income(
                      id: '', // The ID will be generated by Firestore
                      userId: widget.userId,
                      amount: amount,
                      source: source,
                      date: widget.selectedDate ?? DateTime.now(),
                    ),
                  );
                  if (mounted) {
                    Navigator.pop(context);
                  }
                }
              },
            )
          ],
        ),
      ),
    );
  }
}
