
import 'package:flutter/material.dart';
import 'package:myapp/models/expense.dart';
import 'package:myapp/services/firestore_service.dart';

class AddExpense extends StatefulWidget {
  final String userId;
  const AddExpense({super.key, required this.userId});

  @override
  State<AddExpense> createState() => _AddExpenseState();
}

class _AddExpenseState extends State<AddExpense> {
  final _formKey = GlobalKey<FormState>();
  double amount = 0;
  String category = '';

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(20.0),
      child: Form(
        key: _formKey,
        child: Column(
          children: <Widget>[
            const Text(
              'Add a new expense',
              style: TextStyle(fontSize: 18.0, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 20.0),
            TextFormField(
              validator: (val) => val!.isEmpty ? 'Enter a category' : null,
              onChanged: (val) => setState(() => category = val),
              decoration: const InputDecoration(hintText: 'Category'),
            ),
            const SizedBox(height: 20.0),
            TextFormField(
              validator: (val) => val!.isEmpty ? 'Enter an amount' : null,
              onChanged: (val) => setState(() => amount = double.parse(val)),
              decoration: const InputDecoration(hintText: 'Amount'),
              keyboardType: TextInputType.number,
            ),
            const SizedBox(height: 20.0),
            ElevatedButton(
              child: const Text('Add Expense'),
              onPressed: () async {
                if (_formKey.currentState!.validate()) {
                  await FirestoreService().addExpense(
                    Expense(
                      id: '', // The ID will be generated by Firestore
                      userId: widget.userId,
                      amount: amount,
                      category: category,
                      date: DateTime.now(),
                    ),
                  );
                  Navigator.pop(context);
                }
              },
            )
          ],
        ),
      ),
    );
  }
}
